<?php

/*
 * Purpose :	Use the customized captcha object, generated by the Avine system
 * Author :		Stéphane Francel
 *
 * Learn more from the original script : 'securimage_show.php'
 */


// Be ready to get the captcha object from the session
session_start();


// Load library
include 'securimage.php';


if (isset($_SESSION['avine_captcha_object']))
{
	// Return cutomized image
	$img = unserialize($_SESSION['avine_captcha_object']);
	$img->show('backgrounds/bg6.png');
}
else
{
	// Return default image
	$img = new securimage();
	$img->show();
}
