<?php
/* Copyright (C) 2008. All Rights Reserved. @license - Copyrighted Software. Author: Stéphane Francel */


// No direct access
defined( '_DIRECT_ACCESS' ) or die( 'Restricted access' );


// Path info
$path = admin_getPathway();


// Configuration
$start_view = true;
$session = new sessionManager(sessionManager::BACKEND, 'newsletter_list');
$session->init('use_text_editor', false);
$session->init('include_template', true);


// Images Html
$png_css = '<img src="'.WEBSITE_PATH.'/admin/components/com_newsletter/images/css.png" alt="" />';


///////////
// Process

$filter = new formManager_filter();
$filter->requestVariable('post');

// Posted forms possibilities
$submit = formManager::isSubmitedForm('start_', 'post');
if ($submit)
{
	$del = $filter->requestName ('del_'	)->getInteger();
	$upd = $filter->requestName ('upd_'	)->getInteger();
	$new = $filter->requestValue('new'	)->get();
} else {
	$del = false;
	$upd = false;
	$new = false;
}

$upd_submit = formManager::isSubmitedForm('upd_', 'post');



// Case 'del'
if ($del)
{
	if (!$db->select("newsletter_send, id, where: newsletter_id=$del"))
	{
		admin_informResult( $db->delete("newsletter; where: id=$del") );
	}
	else {
		admin_message(LANG_ADMIN_COM_NEWSLETTER_LIST_DEL_ERROR, 'error');
	}
}



// Case 'new'
if ($new)
{
	$n = '';
	while ($db->selectOne("newsletter, id, where: subject=".$db->str_encode(LANG_ADMIN_PROCESS_NEW_DATA_DEFAULT_NAME.$n), 'id')) {
		$n++;
	}

	comConfig_getInfos($site_name, $system_email);
	$config = $db->selectOne('newsletter_config, *');

	$x = 0;
	$id = array('NULL', '1');
	while ( ($x < count($id)) && (!isset($new_id)) )
	{
		if ($db->insert('newsletter; '
					.$id[$x]
					.', '.$db->selectOne("newsletter_tmpl, id(desc)", 'id') # Select last template !
					.', '.$db->str_encode(LANG_ADMIN_PROCESS_NEW_DATA_DEFAULT_NAME.$n)
					.', '.$db->str_encode('')
					.', '.$db->str_encode($system_email)
					.', '.$db->str_encode($config['reply_to'])
					.', '.time()
		)) {
			$new_id = $db->insertID();

			// Go now to the update form !
			$upd = $new_id;
		}
		$x++;
	}
}


// Get the latest com_content elements
$get_latest = new comContent_getLatest();
$latest_content = $get_latest->elementsSummary();


// Case 'upd'
if ($upd_submit)
{
	// Fields validation
	$upd_submit_validation = true;

	$filter->reset();

	// id
	$upd_id = $filter->requestValue('id')->getInteger();

	$tmpl_id	= $filter->requestValue('tmpl_id'	)->getInteger();
	$item		= $filter->requestValue('item'		)->getInteger();
	$subject	= $filter->requestValue('subject'	)->getNotEmpty(1, '', LANG_ADMIN_COM_NEWSLETTER_SUBJECT);
	$message	= $filter->requestValue('message'	)->get();
	$sender		= $filter->requestValue('sender'	)->getEmail(1, '', LANG_ADMIN_COM_NEWSLETTER_SENDER);
	$reply_to	= $filter->requestValue('reply_to'	)->getEmail(1, '', LANG_ADMIN_COM_NEWSLETTER_REPLY_TO);

	if ($session->get('use_text_editor'))
	{
		// Current and updated session for 'include_template'
		$current_include_template = $session->get('include_template');
		$session->set('include_template', ($filter->requestValue('include_template')->get() ? true : false));

		if ($current_include_template)
		{
			// Clean message from body header and body footer !
			$message = explode(LANG_ADMIN_COM_NEWSLETTER_LIST_TMPL_CKEDITOR_SEPARATOR, $message);
			if (count($message) == 3) {
				$message = $message[1];
			}
			// 'include_template' feature has been disabled !
			elseif (!$session->get('include_template') && count($message) == 1) {
				$message = implode('', $message);
			}
			// Separator is missing !
			else {
				$filter->set(false)->getError(LANG_ADMIN_COM_NEWSLETTER_LIST_TMPL_CKEDITOR_SEP_MISSING);
			}
		}
	}

	// Latest_content
	$latest_list = array();
	reset($latest_content);
	foreach($latest_content as $element_id => $element_details)
	{
		if (($latest_order = $filter->requestValue('latest_content_'.$element_id)->getNotEmpty(0)) && formManager_filter::isInteger($latest_order))
		{
			$latest_list[$element_id] = $latest_order;
		}
	}
	if (count($latest_list) && $item)
	{
		// Get item template
		$item_tmpl = $db->selectOne("newsletter_tmpl, item$item, where: id=$tmpl_id", "item$item");

		// Put the item template in a temporary file
		$item_tmpl_path = sitePath().'/admin/components/com_newsletter/temp_item_tmpl.html';
		$ftp = new ftpManager();
		$ftp->write($item_tmpl_path, $item_tmpl);

		// Fill item template with the requested elements
		asort($latest_list);
		reset($latest_list);
		foreach($latest_list as $element_id => $latest_order)
		{
			$template = new templateManager();
			$message .= $template->setTmplPath($item_tmpl_path)->setReplacements($latest_content[$element_id])->process();
		}

		// Remove temporary file
		$ftp->delete($item_tmpl_path);
	}

	// Remove tabulation (generated by ckeditor)
	$message = preg_replace('~(\t)+~', ' ', $message); # optional feature (comment to disable)

	if ($upd_submit_validation = $filter->validated())
	{
		// Update database
		$result_db =
			$db->update("newsletter; "
				."  tmpl_id=$tmpl_id"
				.', subject='	.$db->str_encode($subject	)
				.', message='	.$db->str_encode($message	)
				.', sender='	.$db->str_encode($sender	)
				.', reply_to='	.$db->str_encode($reply_to	)
				."; where: id=$upd_id"
			);

		// Send test
		if ($result_db && $filter->requestValue('send_to_submit')->get())
		{
			if ($send_to = $filter->requestValue('send_to')->getEmail())
			{
				$mail = new emailManager();
				$mail	->addMessageHTML(comNewsletter_tmpl::getMessage($upd_id))
						->addTo($send_to)
						->setSubject($subject)
						->setFrom($sender)
						->setReplyTo($reply_to); # Here missing the setting of the return-path. But this is only a test...

				admin_informResult(
					$mail->send(),
					str_replace('{email}', $send_to, LANG_ADMIN_COM_NEWSLETTER_LIST_SEND_TEST_SUCCESS),
					LANG_ADMIN_COM_NEWSLETTER_LIST_SEND_TEST_FAILURE
				);
			}
			else {
				admin_message(LANG_ADMIN_COM_NEWSLETTER_LIST_SEND_TEST_INVALID_EMAIL, 'warning');
			}
			$upd_submit_validation = false; # Continue to update...
		}
		else {
			admin_informResult($result_db);
		}

		if ($filter->requestValue('record')->get()) {
			$upd_submit_validation = false; # Continue to update...
		}
	}
	else {
		echo $filter->errorMessage();
	}
}
if (($upd) || (($upd_submit) && (!$upd_submit_validation)))
{
	$start_view = false;

	// Title
	echo '<h2>'.LANG_ADMIN_COM_NEWSLETTER_LIST_TITLE_UPDATE.'</h2>';

	// Id
	if ($upd) {
		$upd_id = $upd;
	}

	$current = $db->selectOne("newsletter, *, where: id=$upd_id");

	$html = '';
	$form = new formManager();
	$html .= $form->form('post', $_SERVER['PHP_SELF'].$path, 'upd_');
	$html .= $form->hidden('id', $current['id']);

	/*
	 * Template
	 */
	$fieldset1 = '';

	$fieldset1 .= $form->select('tmpl_id', formManager::selectOption(admin_comNewsletter_tmpl::options(), $current['tmpl_id']), LANG_ADMIN_COM_NEWSLETTER_LIST_SELECT_TMPL);

	$fieldset1 .= "\n<hr />\n";

	/*
	 * Fill the message with the latest com_content items
	 */

	$fieldset2 = $form->select('item', admin_comNewsletter_tmpl::itemOptions(), LANG_ADMIN_COM_NEWSLETTER_LIST_SELECT_ITEM).'<br /><br />';
	$fieldset2 .= '<h3>'.LANG_ADMIN_COM_NEWSLETTER_LIST_LATEST_CONTENT.'</h3>';
	reset($latest_content);
	foreach($latest_content as $element_id => $element_details)
	{
		$fieldset2 .= $form->text('latest_content_'.$element_id, '', $element_details['title'].' ('.$element_details['node_title'].')(right)', '', 'size=2;maxlength=2;update=0').'<br />';
	}
	$fieldset2 .= '<p class="grey">'.LANG_ADMIN_COM_NEWSLETTER_LIST_LATEST_CONTENT_TIPS.'</p>';
	$fieldset2 = jsManager::formDialog($fieldset2, LANG_ADMIN_COM_NEWSLETTER_LIST_LATEST_CONTENT_TITLE, 600, 600);
	// end

	$html .= admin_fieldset($fieldset1.$fieldset2, LANG_ADMIN_COM_NEWSLETTER_LIST_UPD_FIELDSET_TMPL);

	/*
	 * Message
	 */
	$fieldset = '';

	// Subject (remove default value when come from $new)
	$fieldset .= $form->text('subject', isset($new_id) ? '' : $current['subject'], LANG_ADMIN_COM_NEWSLETTER_SUBJECT.'<br />', '', "size=50").'<br /><br />';

	// Message (using WYSIWYG features)
	if ($session->get('use_text_editor'))
	{
		// Get template infos
		admin_comNewsletter_tmpl::parts($current['tmpl_id'], $tmpl_css, $body_header, $body_footer);

		if ($session->get('include_template'))
		{
			// Default message
			$current['message'] or $current['message'] = "\n\n\n<p>".LANG_ADMIN_COM_NEWSLETTER_LIST_TMPL_CKEDITOR_DEFAULT_MESSAGE."</p>\n\n\n";

			// Mssage separator (will be required to clean the message from the $body_header and the $body_footer)
			$sep = LANG_ADMIN_COM_NEWSLETTER_LIST_TMPL_CKEDITOR_SEPARATOR;

			// Include the header and the footer in the message
			$current['message'] = $body_header.$sep. $current['message'] .$sep.$body_footer;
		}

		// Ooh, that's the message !
		$fieldset .= $form->textarea('message', $current['message'], LANG_ADMIN_COM_NEWSLETTER_MESSAGE.'<br />', '', 'cols=120;rows=30;update=0').'<br />';

		// Use ckEditor for the message ?
		$my_CKEditor = new loadMyCkeditor();
		if ($tmpl_css)
		{
			$my_CKEditor->contentCss($tmpl_css); # Use the styles of the template for the WYSIWYG editor

			$fieldset .= '<span class="grey">'.$png_css.LANG_ADMIN_COM_NEWSLETTER_LIST_TMPL_CSS_AVAILABLE_Y.'</span>';
		} else {
			$fieldset .= '<span class="red">'.$png_css.LANG_ADMIN_COM_NEWSLETTER_LIST_TMPL_CSS_AVAILABLE_N.'</span>';
		}
		$fieldset .= $my_CKEditor->addName("message");

		// Add the template in the editor window ?
		$fieldset .=
			'<p class="grey"><br />'.
				$form->checkbox('include_template', $session->get('include_template'), LANG_ADMIN_COM_NEWSLETTER_LIST_INCLUDE_TEMPLATE).
				'<br />'.LANG_ADMIN_COM_NEWSLETTER_LIST_INCLUDE_TEMPLATE_TIPS.
			'</p>';
	}
	else {
		// Message (using simple textarea)
		$fieldset .= $form->textarea('message', $current['message'], LANG_ADMIN_COM_NEWSLETTER_MESSAGE.'<br />', '', 'cols=120;rows=30;update=0').'<br />';
	}

	$html .= admin_fieldset($fieldset, LANG_ADMIN_COM_NEWSLETTER_LIST_UPD_FIELDSET_MESSAGE);

	/*
	 * Sender
	 */
	$fieldset = '';

	// Sender, reply_to
	$fieldset .= $form->text('sender'	, $current['sender'		], LANG_ADMIN_COM_NEWSLETTER_SENDER		.'<br />', '', 'size=default').'<br /><br />';
	$fieldset .= $form->text('reply_to'	, $current['reply_to'	], LANG_ADMIN_COM_NEWSLETTER_REPLY_TO	.'<br />').'<br /><br />';

	$html .= admin_fieldset($fieldset, LANG_ADMIN_COM_NEWSLETTER_LIST_UPD_FIELDSET_SENDER);

	/*
	 * Send a test to email address
	 */
	$fieldset = '';

	comConfig_getInfos($site_name, $system_email);
	$fieldset .= $form->text('send_to', $system_email, LANG_ADMIN_COM_NEWSLETTER_SUBSCRIBER_EMAIL);
	$fieldset .= $form->submit('send_to_submit', LANG_ADMIN_COM_NEWSLETTER_BUTTON_SEND);

	$html .= admin_fieldset($fieldset, LANG_ADMIN_COM_NEWSLETTER_LIST_UPD_FIELDSET_SEND_TEST);

	$html .= $form->submit('submit', LANG_ADMIN_BUTTON_SUBMIT);
	$html .= $form->submit('record', LANG_ADMIN_BUTTON_RECORD);
	$html .= $form->end();
	echo $html;
}



//////////////
// Start view

if ($submit && $filter->requestValue('use_text_editor')->get())
{
	$session->set('use_text_editor', !$session->get('use_text_editor')); # Switch mode !
}

if ($start_view)
{
	// Title
	echo '<h2>'.LANG_ADMIN_COM_NEWSLETTER_LIST_TITLE_START.'</h2>';

	$html = '';

	// Form
	$form = new formManager();
	$html .= $form->form('post', $_SERVER['PHP_SELF'].$path, 'start_');

	if (!$db->selectCount("newsletter_tmpl"))
	{
		admin_message(LANG_ADMIN_COM_NEWSLETTER_LIST_NO_TMPL_DEFINED, 'warning');
	}
	else
	{
		// Database
		$newsletter = $db->select('newsletter, id,subject,date_creation(desc)');

		for ($i=0; $i<count($newsletter); $i++)
		{
			$href = siteUrl().'/components/com_newsletter/online.php?id='.$newsletter[$i]['id'];
			$newsletter[$i]['subject'] = "<a href=\"$href\" title=\"$href\" class=\"external\">{$newsletter[$i]['subject']}</a>";

			$newsletter[$i]['date_creation'] = getTime($newsletter[$i]['date_creation'], 'time=no');

			$update[$i] = $form->submit('upd_'.$newsletter[$i]['id'], LANG_ADMIN_BUTTON_UPDATE, '', 'image=update'); // (2)
			$delete[$i] = $form->submit('del_'.$newsletter[$i]['id'], LANG_ADMIN_BUTTON_DELETE, '', 'image=delete'); // (3)
		}

		// Table
		$table = new tableManager($newsletter);

		if (count($newsletter)) {
			$table->addCol($delete, 0);
			$table->addCol($update, 999);
		}

		$table->header(array('', 'ID', LANG_ADMIN_COM_NEWSLETTER_SUBJECT, LANG_ADMIN_COM_NEWSLETTER_DATE_CREATION, ''));

		#$table->delCol(1); # Delete the 'id' column
		$html .= $table->html();

		$html .= $form->submit('new', LANG_ADMIN_BUTTON_CREATE);

		// Use text editor ?
		if ($session->get('use_text_editor')) {
			$use_text_editor = LANG_ADMIN_COM_NEWSLETTER_LIST_USE_TEXT_EDITOR_N;
		} else {
			$use_text_editor = LANG_ADMIN_COM_NEWSLETTER_LIST_USE_TEXT_EDITOR_Y;
		}
		$html .= $form->submit('use_text_editor', $use_text_editor);
	}

	$html .= $form->end();
	echo $html;
}

echo '<br /><br /><a href="'.$_SERVER['PHP_SELF'].$path.'">'.LANG_ADMIN_BUTTON_REFRESH.'</a>';

?>